"""
wall_texture.py — WallTexture: vertical-strip texture sampling for RaycastCanvas.

Pre-samples an image (or colour array) into N vertical colour strips so wall
columns can be textured with a single LUT lookup per ray — no per-pixel work
at render time.

Pillow is **optional**.  Two factory constructors are provided:

* ``WallTexture.from_colors(light)`` — the default, zero-dependency path.
  Pass a list of hex colour strings (one per vertical strip).  Dark-side
  colours are auto-generated by darkening each strip.

* ``WallTexture.from_image(path)`` — uses Pillow to open an image, resize it
  to ``strips × 1`` pixels, and sample each column's average colour.  Raises
  ``ImportError`` if Pillow (``Pillow``) is not installed.

Quick start::

    from flet_game import WallTexture

    # Option A — single colour (fills all 32 strips uniformly, zero-dependency)
    brick = WallTexture.from_colors("#8b4513")

    # Option B — custom strip array (no Pillow)
    brick = WallTexture.from_colors([
        "#8b4513", "#a0522d", "#8b4513", "#704214",
        "#8b4513", "#a0522d", "#8b4513", "#704214",
    ])

    # Option C — load from image file (requires Pillow)
    stone = WallTexture.from_image("assets/textures/stone.png", strips=32)

    # Use with RaycastCanvas
    rc = RaycastCanvas(
        ...,
        wall_textures=[brick, stone],  # indexed by wall type 1, 2, …
    )
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Optional


def _parse_hex(color: str) -> tuple[int, int, int]:
    c = color.lstrip("#")
    return int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16)


def _to_hex(r: int, g: int, b: int) -> str:
    return f"#{r:02x}{g:02x}{b:02x}"


@functools.lru_cache(maxsize=512)
def _darken(color: str, factor: float = 0.65) -> str:
    """Darken a hex colour by a factor (0.0–1.0)."""
    r, g, b = _parse_hex(color)
    return _to_hex(int(r * factor), int(g * factor), int(b * factor))


class WallTexture:
    """Pre-sampled vertical colour strips for textured wall rendering.

    Each texture is stored as two parallel lists of hex colour strings:
    ``_light`` (normal side) and ``_dark`` (Y-side darkened).  At render
    time, ``sample(u)`` returns the pair for a given U coordinate in
    O(1) — just an array index lookup.

    Parameters
    ----------
    strips : int
        Number of vertical colour samples (default 32).
    """

    def __init__(self, strips: int = 32) -> None:
        self._strips = strips
        self._light: list[str] = []
        self._dark: list[str] = []
        self._grid_light: Optional[list[list[str]]] = None
        self._grid_dark: Optional[list[list[str]]] = None

    # ── Factory constructors ──────────────────────────────────────────────

    @classmethod
    def from_colors(
        cls,
        light: str | list[str],
        dark: Optional[str | list[str]] = None,
        strips: int = 32,
        darken_factor: float = 0.65,
    ) -> "WallTexture":
        """Create a texture from colour(s).

        Parameters
        ----------
        light : str or list[str]
            Single hex colour string (fills all strips uniformly) OR a list
            of hex colour strings (one per vertical strip).  List length
            determines the strip count.
        dark : str or list[str] | None
            Optional dark-side colours.  If ``None``, each ``light`` colour
            is automatically darkened by ``darken_factor``.
        strips : int
            Number of vertical strips when ``light`` is a single string
            (default 32).  Ignored when ``light`` is a list.
        darken_factor : float
            Multiplier applied to each RGB channel when auto-generating
            dark-side colours.  Default 0.65 (35% darker).

        Returns
        -------
        WallTexture
        """
        if isinstance(light, str):
            # Single colour — fill all strips uniformly
            tex = cls(strips=strips)
            tex._light = [light] * strips
            if dark is not None:
                d = dark if isinstance(dark, str) else dark[0]
                tex._dark = [d] * strips
            else:
                tex._dark = [_darken(light, darken_factor)] * strips
        else:
            # List of colours — one per strip
            tex = cls(strips=len(light))
            tex._light = list(light)
            if dark is not None:
                if isinstance(dark, str):
                    tex._dark = [dark] * len(light)
                else:
                    tex._dark = list(dark)
            else:
                tex._dark = [_darken(c, darken_factor) for c in light]
        return tex

    @classmethod
    def from_grid(
        cls,
        rows: list[list[str]],
        dark: Optional[list[list[str]]] = None,
        darken_factor: float = 0.65,
    ) -> "WallTexture":
        """Create a 2-D tile-grid texture (horizontal + vertical detail).

        Parameters
        ----------
        rows : list[list[str]]
            Top-to-bottom list of rows; each row is a list of hex colour
            strings, one per vertical strip.  Row count determines the
            vertical resolution (e.g. 8 rows = 8 tile bands).  All rows
            must have the same length.
        dark : list[list[str]] | None
            Optional dark-side grid.  If ``None``, every light colour is
            auto-darkened by ``darken_factor``.
        darken_factor : float
            Multiplier for auto-generated dark-side colours.

        The 1-D strip arrays (``sample(u)``) are filled with each strip's
        vertical average so the canvas backend (vertical strips only)
        degrades gracefully.

        Returns
        -------
        WallTexture
        """
        n_rows = len(rows)
        n_strips = len(rows[0])
        tex = cls(strips=n_strips)
        tex._grid_light = [list(r) for r in rows]
        if dark is not None:
            tex._grid_dark = [list(r) for r in dark]
        else:
            tex._grid_dark = [
                [_darken(c, darken_factor) for c in r] for r in rows
            ]
        avg_light = []
        avg_dark = []
        for s in range(n_strips):
            lr = lb = lg = 0
            dr = db = dg = 0
            for r in range(n_rows):
                pr, pg, pb = _parse_hex(rows[r][s])
                lr += pr
                lg += pg
                lb += pb
                qr, qg, qb = _parse_hex(tex._grid_dark[r][s])
                dr += qr
                dg += qg
                db += qb
            avg_light.append(_to_hex(lr // n_rows, lg // n_rows, lb // n_rows))
            avg_dark.append(_to_hex(dr // n_rows, dg // n_rows, db // n_rows))
        tex._light = avg_light
        tex._dark = avg_dark
        return tex

    @classmethod
    def from_image(
        cls,
        path: str,
        strips: int = 32,
        darken_factor: float = 0.65,
    ) -> "WallTexture":
        """Create a texture by sampling an image file with Pillow.

        The image is resized to ``strips × 1`` pixels and each column's
        average RGB colour is extracted.

        Parameters
        ----------
        path : str
            Path to the image file (PNG, JPG, etc.).
        strips : int
            Number of vertical samples (default 32).
        darken_factor : float
            Multiplier for auto-generated dark-side colours.

        Raises
        ------
        ImportError
            If Pillow (``Pillow``) is not installed.

        Returns
        -------
        WallTexture
        """
        try:
            from PIL import Image as PILImage
        except ImportError:
            raise ImportError(
                "Pillow is required for WallTexture.from_image(). "
                "Install it with: pip install Pillow\n"
                "Or use WallTexture.from_colors() instead (no dependencies)."
            )

        img = PILImage.open(path).convert("RGB")
        # Resize to strips × 1 — each pixel column is one strip sample.
        img = img.resize((strips, 1), resample=PILImage.LANCZOS)
        pixels = list(img.getdata())  # list of (R, G, B) tuples

        light = [_to_hex(r, g, b) for r, g, b in pixels]
        return cls.from_colors(light, darken_factor=darken_factor)

    # ── Sampling ────────────────────────────────────────────────────────

    @property
    def has_grid(self) -> bool:
        """True when this texture carries a 2-D tile grid (see ``from_grid``)."""
        return self._grid_light is not None

    @property
    def grid_light(self) -> Optional[list[list[str]]]:
        """Top-to-bottom rows of light-side hex colours, or ``None``."""
        return self._grid_light

    @property
    def grid_dark(self) -> Optional[list[list[str]]]:
        """Top-to-bottom rows of dark-side hex colours, or ``None``."""
        return self._grid_dark

    def sample_uv(self, u: float, v: float) -> tuple[str, str]:
        """Return ``(light_color, dark_color)`` for texture coords (u, v).

        ``u`` is horizontal 0.0–1.0, ``v`` is vertical 0.0 (top) – 1.0
        (bottom).  Falls back to ``sample(u)`` when the texture has no
        2-D grid.
        """
        if self._grid_light is None or self._grid_dark is None:
            return self.sample(u)
        rows = len(self._grid_light)
        r = min(int(v * rows), rows - 1)
        r = max(0, r)
        c = min(int(u * self._strips), self._strips - 1)
        c = max(0, c)
        return self._grid_light[r][c], self._grid_dark[r][c]

    def sample(self, u: float) -> tuple[str, str]:
        """Return ``(light_color, dark_color)`` for a U coordinate in 0.0–1.0.

        Parameters
        ----------
        u : float
            Horizontal texture coordinate, 0.0 (left edge) to 1.0 (right edge).
            Values outside 0–1 are clamped.

        Returns
        -------
        tuple[str, str]
            ``(light_hex, dark_hex)`` colour strings.
        """
        idx = min(int(u * self._strips), self._strips - 1)
        idx = max(0, idx)
        return self._light[idx], self._dark[idx]

    # ── Properties ───────────────────────────────────────────────────────

    @property
    def strips(self) -> int:
        """Number of vertical colour samples."""
        return self._strips

    @property
    def colors(self) -> list[str]:
        """The light-side colour array (read-only copy)."""
        return list(self._light)

    @property
    def dark_colors(self) -> list[str]:
        """The dark-side colour array (read-only copy)."""
        return list(self._dark)
